spring:
  h2:
    console:
      enabled: true
      path: /console-h2
  datasource:
    username: custom_user
    password: strongPassword
    url: jdbc:h2:mem:my_database
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
