INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Amadeusz', 'Nos', 'PULMONOLOGY', 0);--1
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Zbigniew', 'Wasicki', 'PULMONOLOGY', 0);--2
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Dorota', 'Kalisz', 'PSYCHIATRY', 0);--3
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Karol', 'Lipski', 'PULMONOLOGY', 0);--4
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Adam', 'Holicki', 'PSYCHIATRY', 0);--5
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Tomek', 'Grabiuk', 'CARDIOLOGY', 0);--6
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Stanislaw', 'Rajski', 'DERMATOLOGY', 0);--7
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Karolina', 'Troc', 'FAMILY_MEDICINE', 0);--8
INSERT INTO DOCTOR (NAME, LAST_NAME, SPECIALIZATION, VERSION) VALUES ('Patrycja', 'Czarnik', 'HERMATOLOGY', 0);--9

INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Antoni', 'Koleczko', 0);--1
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Beata', 'Bosch', 0);--2
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Elzbieta', 'Holicka', 0);--3
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Franciszek', 'Zagubcki', 0);--4
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Wlodek', 'Anistalowski', 0);--5
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Patrycja', 'Koluszko', 0);--6
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Hubert', 'Moniusz', 0);--7
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Jadwiga', 'Moniusz', 0);--8
INSERT INTO PATIENT (NAME, LAST_NAME, VERSION) VALUES ('Krystyna', 'Moniusz', 0);--9


INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-01-15 18:17', 'ASTHMA', 30, 1, 3, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-01-05 15:27', 'ASTHMA', 30, 1, 4, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-04-12 10:45', 'ASTHMA', 45, 2, 5, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-06-12 09:25', 'ASTHMA', 10, 2, 2, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-12-12 15:25', 'ASTHMA', 60, 2, 3, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-08-16 10:42', 'ANXIETY', 15, 3, 2, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-09-07 09:55', 'ASTHMA', 15, 3, 2, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-07-17 12:21', 'CHOLESTEROL_PROBLEM', 15, 7, 6, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-08-23 10:42', 'CHOLESTEROL_PROBLEM', 45, 7, 2, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-09-27 12:04', 'CHOLESTEROL_PROBLEM', 15, 7, 7, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-01-14 20:30', 'DIABETE', 60, 8, 7, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-04-04 09:11', 'DIABETE', 45, 8, 5, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-06-18 20:30', 'DIABETE', 45, 8, 2, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-12-21 08:02', 'DIABETE', 45, 8, 8, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2025-11-05 12:00', 'DIABETE', 45, 8, 9, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-10-05 20:42', 'ANXIETY', 15, 5, 6, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-12-25 07:42', 'ANXIETY', 45, 5, 1, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-05-27 05:42', 'ANXIETY', 30, 5, 4, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2025-08-02 21:25', 'MIGRAINE', 30, 8, 5, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-05-02 15:52', 'MIGRAINE', 30, 8, 4, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-09-02 14:33', 'MIGRAINE', 30, 8, 1, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2024-09-25 15:51', 'HIGH_BLOOD_PRESSURE', 15, 9, 4, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2025-12-08 18:34', 'HIGH_BLOOD_PRESSURE', 45, 9, 7, false);
INSERT INTO APPOINTMENT (TERM, REASON_FOR_VISIT, APPOINTMENT_TIME, DOCTOR_ID, PATIENT_ID, DELETED) VALUES ('2026-05-05 12:53', 'HIGH_BLOOD_PRESSURE', 60, 9, 6, false);
